export const POST_SURVEY_QUESTIONS = {
  participantId: {
    id: "participantId",
    label: "Enter your participant ID",
    type: "text" as const,
    required: true,
  },
  aiTrust: {
    id: "aiTrust",
    label:
      "How likely are you to trust the AI responses you get when you ask it a question after this experiment?",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Least Likely",
    maxLabel: "Most Likely",
    required: true,
  },
  aiPotential: {
    id: "aiPotential",
    label:
      "How do you perceive the potential of AI in question answering after this experiment?",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Not Effective",
    maxLabel: "Highly Beneficial",
    required: true,
  },
  topic1L: {
    id: "topic1L",
    label: "Freedom of speech should be protected even when it offends others.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic1R: {
    id: "topic1R",
    label: "Freedom of speech should be limited when it offends others.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic2L: {
    id: "topic2L",
    label: "Healthcare should be a universal right for everyone.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic2R: {
    id: "topic2R",
    label:
      "Healthcare should be treated as a personal responsibility, not a universal right.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic3L: {
    id: "topic3L",
    label: "Human activity is the primary cause of climate change.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic3R: {
    id: "topic3R",
    label: "Climate change is mostly a natural process, not caused by humans.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic4L: {
    id: "topic4L",
    label:
      "Immigration generally strengthens the country and should be expanded.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic4R: {
    id: "topic4R",
    label: "Immigration generally harms the country and should be restricted.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
};
