export const PRE_SURVEY_QUESTIONS = {
  participantId: {
    id: "participantId",
    label: "Enter your participant ID",
    type: "text" as const,
    required: true,
  },
  aiTrust: {
    id: "aiTrust",
    label:
      "How likely are you to trust the AI responses you get when you ask it a question?",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Least Likely",
    maxLabel: "Most Likely",
    required: true,
  },
  aiPotential: {
    id: "aiPotential",
    label: "How do you perceive the potential of AI in question answering?",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Not Effective",
    maxLabel: "Highly Beneficial",
    required: true,
  },
  politicalOrientation: {
    id: "politicalOrientation",
    label:
      "How would you describe your general views on political or social issues?",
    type: "radio" as const,
    required: false,
    options: [
      { value: "1", label: "1. Very liberal" },
      { value: "2", label: "2. Liberal" },
      { value: "3", label: "3. Slightly liberal" },
      { value: "4", label: "4. Moderate (neither liberal nor conservative)" },
      { value: "5", label: "5. Slightly conservative" },
      { value: "6", label: "6. Conservative" },
      { value: "7", label: "7. Very conservative" },
    ],
  },
  topic1L: {
    id: "topic1L",
    label: "Freedom of speech should be protected even when it offends others.",
    sublabel: "How do you agree or disagree with discussion topic 1L.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic1R: {
    id: "topic1R",
    label: "Freedom of speech should be limited when it offends others.",
    sublabel: "How do you agree or disagree with discussion topic 1R.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic2L: {
    id: "topic2L",
    label: "Healthcare should be a universal right for everyone.",
    sublabel: "How do you agree or disagree with discussion topic 2L.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic2R: {
    id: "topic2R",
    label:
      "Healthcare should be treated as a personal responsibility, not a universal right.",
    sublabel: "How do you agree or disagree with discussion topic 2R.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic3L: {
    id: "topic3L",
    label: "Human activity is the primary cause of climate change.",
    sublabel: "How do you agree or disagree with discussion topic 3L.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic3R: {
    id: "topic3R",
    label: "Climate change is mostly a natural process, not caused by humans.",
    sublabel: "How do you agree or disagree with discussion topic 3R.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic4L: {
    id: "topic4L",
    label:
      "Immigration generally strengthens the country and should be expanded.",
    sublabel: "How do you agree or disagree with discussion topic 4L.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
  topic4R: {
    id: "topic4R",
    label: "Immigration generally harms the country and should be restricted.",
    sublabel: "How do you agree or disagree with discussion topic 4R.",
    type: "likert" as const,
    min: 1,
    max: 7,
    minLabel: "Strongly Agree",
    maxLabel: "Strongly Disagree",
    required: true,
  },
};
